import { describe, expect, it } from "vitest"

import { getLiveAlerts } from "../data"

// Roadmap phase 18 requirement 2 / acceptance criterion: every notification
// generated by the system must carry at least one concrete action, never
// just a bare description. Mock mode is the only alert-generation path this
// suite can exercise without a live Supabase project (see docs/notifications.md
// for the same live-data caveat every phase since 03 has carried), but it
// covers 6 of the 9 live-alert types — the remaining 3
// (vehicle_document_expiring, licence_expiring, vehicle_unavailable_upcoming_reservation)
// are exercised by lib/notifications/__tests__/actions.test.ts's direct
// coverage of the shared callAndOpenActions helper they all build on.
describe("getLiveAlerts — every alert has a concrete action", () => {
  it("never returns an alert with an empty actions array", async () => {
    const alerts = await getLiveAlerts("mock-company", {
      maintenanceReminderDays: 365,
      documentExpiryWarningDays: 365,
      overdueGracePeriodHours: 0,
    })

    expect(alerts.length).toBeGreaterThan(0)
    for (const alert of alerts) {
      expect(alert.actions.length).toBeGreaterThan(0)
    }
  })

  it("gives the overdue-rental alert both a call and an open action, since mock fixtures carry a phone number", async () => {
    const alerts = await getLiveAlerts("mock-company", {
      maintenanceReminderDays: 365,
      documentExpiryWarningDays: 365,
      overdueGracePeriodHours: 0,
    })

    const overdue = alerts.find((a) => a.type === "rental_overdue")
    expect(overdue).toBeDefined()
    expect(overdue!.actions.some((a) => a.kind === "call")).toBe(true)
    expect(overdue!.actions.some((a) => a.kind === "link")).toBe(true)
  })
})
