-- Roadmap phase 46 (Customer Communication Timeline). Adds the 6 new
-- activity_log types "what have we already done with this customer?"
-- needs (5 WhatsApp actions from phase 45 + a manually-logged call) to
-- the existing type CHECK constraint, mirroring types/rental.ts's
-- ACTIVITY_TYPES array (see lib/__tests__/activity-log.test.ts's
-- drift-guard test, which now asserts this exact list).
alter table public.activity_log drop constraint activity_log_type_check;
alter table public.activity_log add constraint activity_log_type_check check (type in (
  'reservation_requested',
  'reservation_confirmed',
  'reservation_status_changed',
  'reservation_updated',
  'reservation_cancelled',
  'payment_recorded',
  'payment_refunded',
  'vehicle_picked_up',
  'vehicle_returned',
  'vehicle_status_changed',
  'maintenance_completed',
  'customer_created',
  'customer_updated',
  'document_uploaded',
  'member_invited',
  'pickup_started',
  'return_started',
  'inspection_completed',
  'inspection_corrected',
  'damage_recorded',
  'damage_resolved',
  'deposit_collected',
  'deposit_returned',
  'deposit_retained',
  'maintenance_scheduled',
  'vehicle_entered_maintenance',
  'maintenance_cancelled',
  'expense_recorded',
  'user_suspended',
  'user_reactivated',
  'user_removed',
  'invitation_accepted',
  'rental_extended',
  'contract_generated',
  'contract_signed',
  'contract_prepared',
  'contract_sent_for_signature',
  'contract_activated',
  'contract_completed',
  'contract_archived',
  'contract_cancelled',
  'contract_amended',
  'contract_viewed',
  'contract_printed',
  'contract_downloaded',
  'template_created',
  'template_version_activated',
  'document_viewed',
  'document_downloaded',
  'permission_override_granted',
  'permission_override_revoked',
  -- New for phase 46:
  'whatsapp_confirmation_sent',
  'whatsapp_pickup_reminder_sent',
  'whatsapp_return_reminder_sent',
  'whatsapp_payment_reminder_sent',
  'whatsapp_contract_sent',
  'call_logged'
));
